"""Pydantic schemas for data validation and structured LLM outputs."""

from typing import Literal
from pydantic import BaseModel, Field, field_validator


class SupportAnalysis(BaseModel):
    """Structured output generated by the AI copilot analysis chain."""

    intent: str = Field(
        ...,
        description="Core intent of the customer request (e.g., 'Duplicate Charge', 'Refund Request', 'Delayed Shipment', 'Account Cancellation', 'Product Inquiry').",
    )
    sentiment: str = Field(
        ...,
        description="Detected customer sentiment (e.g., 'Frustrated', 'Neutral', 'Inquiring', 'Urgent').",
    )
    priority: Literal["low", "medium", "high"] = Field(
        ...,
        description="Assessed issue priority level based on customer tier, financial impact, and SLA rules.",
    )
    summary: str = Field(
        ...,
        description="Concise 1-2 sentence distillation of the customer's situation and request.",
    )
    recommended_action: str = Field(
        ...,
        description="Precise operational next step for the human support agent to execute or verify.",
    )
    requires_human_review: bool = Field(
        ...,
        description="True if the request exceeds automated policy thresholds, involves disputes, safety, or ambiguity.",
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score between 0.0 and 1.0 indicating model grounding in context.",
    )
    sources: list[str] = Field(
        default_factory=list,
        description="List of specific knowledge base documents/sections referenced (e.g., ['Billing Policy > Duplicate Charges']).",
    )
    draft_response: str = Field(
        ...,
        description="Polished, empathetic, grounded draft response for the agent to review and send.",
    )

    @field_validator("confidence")
    @classmethod
    def clamp_confidence(cls, v: float) -> float:
        """Ensure confidence is strictly bounded between 0.0 and 1.0."""
        return max(0.0, min(1.0, round(v, 2)))


class CustomerSchema(BaseModel):
    """Customer profile record."""
    id: str
    name: str
    email: str
    plan: str
    status: str
    joined_at: str


class OrderSchema(BaseModel):
    """Customer order record."""
    id: str
    customer_id: str
    product: str
    amount: float
    status: str
    created_at: str


class PaymentSchema(BaseModel):
    """Payment transaction record."""
    id: str
    customer_id: str
    order_id: str
    amount: float
    status: str
    created_at: str


class KnowledgeChunk(BaseModel):
    """Retrieved policy knowledge snippet."""
    content: str
    source: str
    section: str
    relevance_score: float = 0.0
